### ISSUE TITLE
SpeakerHub Support?

### ISSUE THREAD

**Issue by gtalarico** [YoSmart-Inc/yolink-api#1]
Hi folks - 
Are there plans to add support for Speaker Hub? 
I am particularly interested in PlayAudio.
http://doc.yosmart.com/docs/yolinkapi/SpeakerHub/#3speakerhubplayaudio

Currently using yolink via home assistant. I was able to send audio via a IFTT integration but would prefer to send it directly.
PS: @matrixd2 who is code owner in HASS

**Comment by blamejoel** [comment]
Seems this was being worked on at some point... https://github.com/YoSmart-Inc/core/commit/ea64f68cbb5f09136db8174e22b3e9cc5a340b15

**Comment by matrixd2** [comment]
Integration has added SpeakerHub support
