### ISSUE TITLE
Endpoints Dictionary Key Naming Convention Error

### ISSUE THREAD

**Issue by Lucian-Williamson** [YoSmart-Inc/yolink-api#10]
Issue [here](https://github.com/YoSmart-Inc/yolink-api/blob/main/yolink/home_manager.py#L92C12-L92C53) and [here](https://github.com/YoSmart-Inc/yolink-api/blob/main/yolink/home_manager.py#L60)

In the `HomeManager` class of the YoLink API, there's an issue where endpoints with the same name but different device IDs aren't handled correctly. Device names are not guaranteed to be unique, e.g. a user would not typically rename multiple speak hubs. The [device object](https://github.com/YoSmart-Inc/yolink-api/blob/main/yolink/device.py#L58) is already storing this data.

**Comment by matrixd2** [comment]
HomeManager saves the endpoints used by the device. It is only used for mqtt message subscriptions, devices with the same endpoint are all connected to the same mqtt broker.

**Comment by Lucian-Williamson** [comment]
I'm referring to separate devices here that share the same name, but have a different `deviceID`, `UDID`, and `token`. These should have different endpoints.

**Comment by matrixd2** [comment]
Our device model names are unique. Normally, UC model devices are connected to US endpoints, and EC model devices are connected to European endpoints.

**Comment by Lucian-Williamson** [comment]
Here is a sample response from:
``` python
 response: BRDP = await self._http_client.execute(
            url=Endpoints.US.value.url, bsdp={"method": "Home.getDeviceList"}, **kwargs
        )
```
```
{dict: 7} {'deviceId': '', 'deviceUDID': '', 'modelName': 'YS1604-UC', 'name': 'Speaker Hub', 'parentDeviceId': None, 'token': '', 'type': 'SpeakerHub'}
{dict: 7} {'deviceId': '', 'deviceUDID': '', 'modelName': 'YS1604-UC', 'name': 'Speaker Hub', 'parentDeviceId': None, 'token': '', 'type': 'SpeakerHub'}
```

It appears that the device model names and the names are not unique, which is being used [here](https://github.com/YoSmart-Inc/yolink-api/blob/main/yolink/home_manager.py#L92C12-L92C53).

**Comment by matrixd2** [comment]
Sorry, I think I didn't understand what you mean

'modelName': 'YS1604-UC'

It means this device is 'UC' version(America), default device endpoint is `Endpoints.US`
In your case, these two speaker hub using the same endpoint `Endpoints.US`

in `HomeManager`, we just need to connect to `Endpoints.US` mqtt broker, We can subscribe to the messages of these two devices

**Comment by matrixd2** [comment]
> I'm referring to separate devices here that share the same name, but have a different `deviceID`, `UDID`, and `token`. These should have different endpoints.

The device endpoint is only related to the device model. The endpoint is the location of our server, such as the US(America) or (EU) Europe

**Comment by Lucian-Williamson** [comment]
It appears, [the above code in question](https://github.com/YoSmart-Inc/yolink-api/blob/main/yolink/home_manager.py#L92-L94), was simply function as a sort of 'bool' for [async_setup](https://github.com/YoSmart-Inc/yolink-api/blob/main/yolink/home_manager.py#L49)

I was led to believe there was an error hear from a `aiomqtt.Client`. I'm seeing repetitions on. It's clear that I was confused about the original function of the code, and that there is not an underlying error.

Apologies, thanks for the clarification!
